### ISSUE TITLE
[mingw-w64-latexila] 3.20.0 fails to build

### ISSUE THREAD

**Issue by aphirst** [Alexpux/MINGW-packages#1708]
As the current package fails to run due to a mismatch in libgspell versions (and pango problems on mati865's machine), I decided to try to do a build of the most recent version of latexila, 3.20.0. It turned out that just changing the version number didn't work, as the .patch referenced by the PKGBUILD fails to apply. Commenting out the application of the patch, installing `itstool` as requested by the configure scripts, and then re-attempting a build results in the following output after a few minutes:

```
Assembler messages:
Fatal error: can't create tmp-introspects_gjb3/msys64/home/[username]/MINGW-packages/mingw-w64-latexila/src/build-x86_64-w64-mingw32/src/liblatexila/tmp-introspects_gjb3/Latexila-Latexila.o: No such file or directory
C:/msys64/home/[username]/MINGW-packages/mingw-w64-latexila/src/build-x86_64-w64-mingw32/src/liblatexila/tmp-introspects_gjb3/Latexila-Latexila.c:645:1: fatal error: error writing to -: Invalid argument
 };
 ^
compilation terminated.
Traceback (most recent call last):
  File "C:/msys64/mingw64/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 545, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 419, in create_binary
    gdump_parser.get_error_quark_functions())
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/dumper.py", line 328, in compile_introspection_binary
    return dc.run()
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/dumper.py", line 167, in run
    introspection_obj = self._compile(c_path)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/dumper.py", line 207, in _compile
    self._options.init_sections)
  File "C:/msys64/mingw64/bin/../lib/gobject-introspection/giscanner/ccompiler.py", line 241, in compile
    source_str.rfind(os.sep)]))
  File "C:/msys64/mingw64/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "C:/msys64/mingw64/lib/python2.7/distutils/cygwinccompiler.py", line 189, in _compile
    raise CompileError, msg
distutils.errors.CompileError: command 'C:\\msys64\\mingw64\\bin/x86_64-w64-mingw32-gcc.exe' failed with exit status 1
make[5]: *** [C:/msys64/mingw64/share/gobject-introspection-1.0/Makefile.introspection:174: Latexila.gir] Fehler 1
make[5]: Verzeichnis „/home/[username]/MINGW-packages/mingw-w64-latexila/src/build-x86_64-w64-mingw32/src/liblatexila“ wird verlassen
make[4]: *** [Makefile:469: all] Fehler 2
make[4]: Verzeichnis „/home/[username]/MINGW-packages/mingw-w64-latexila/src/build-x86_64-w64-mingw32/src/liblatexila“ wird verlassen
make[3]: *** [Makefile:1486: all-recursive] Fehler 1
make[3]: Verzeichnis „/home/[username]/MINGW-packages/mingw-w64-latexila/src/build-x86_64-w64-mingw32/src“ wird verlassen
make[2]: *** [Makefile:539: all] Fehler 2
make[2]: Verzeichnis „/home/[username]/MINGW-packages/mingw-w64-latexila/src/build-x86_64-w64-mingw32/src“ wird verlassen
make[1]: *** [Makefile:552: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/[username]/MINGW-packages/mingw-w64-latexila/src/build-x86_64-w64-mingw32“ wird verlassen
make: *** [Makefile:482: all] Fehler 2
```

If you need any more info feel free to ask.

**Comment by DavidEGrayson** [comment]
If MSYS2 has a package for this "itstool" utility that mentioned, you should add it to the appropriate list in the PKGBUILD (`makedepends` or `depends` if I recall correctly).

**Comment by KrullKorg** [comment]
it seems the classic error when path is too long (create a symbolic link in msys2 root)

**Comment by achadwick** [comment]
Just a note here to say that from my experience, you need to make the hack symlinks with CMD and mklink. Cygwin-style `ln -s` just makes a copy.

```
C:\msys64>mklink /d 1 usr\src\MINGW-packages\mingw-w64-gobject-introspection
symbolic link created for 1 <<===>> usr\src\MINGW-packages\mingw-w64-gobject-introspection
```

(Introspection, introspect thyself...)

**Comment by achadwick** [comment]
A better fix is to use `BUILDDIR`: <https://wiki.archlinux.org/index.php/Makepkg#tmpfs>.

@aphirst 
Please try again with the new `gobject-introspection` and with BUILDDIR and/or a shorter path.

**Comment by aphirst** [comment]
I ran `BUILDDIR=/tmp/makepkg makepkg` but got another error:

```
make[4]: Verzeichnis „/tmp/makepkg/mingw-w64-latexila/src/build-x86_64-w64-mingw32/src/evince“ wird betreten
  GEN      evince-gdbus-generated.c
  GEN      evince-gdbus-generated.h
Traceback (most recent call last):
  File "C:/msys64/mingw64/bin/gdbus-codegen", line 39, in <module>
    sys.exit(codegen_main.codegen_main())
  File "C:/msys64/mingw64/share/glib-2.0/codegen/codegen_main.py", line 189, in codegen_main
    c = open(c_code + '.c', 'w')
IOError: [Errno 22] invalid mode ('w') or filename: 'evince-gdbus-generated.c'
make[4]: *** [Makefile:675: evince-gdbus-generated.h] Fehler 1
make[4]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[4]: Verzeichnis „/tmp/makepkg/mingw-w64-latexila/src/build-x86_64-w64-mingw32/src/evince“ wird verlassen
make[3]: *** [Makefile:1486: all-recursive] Fehler 1
make[3]: Verzeichnis „/tmp/makepkg/mingw-w64-latexila/src/build-x86_64-w64-mingw32/src“ wird verlassen
make[2]: *** [Makefile:539: all] Fehler 2
make[2]: Verzeichnis „/tmp/makepkg/mingw-w64-latexila/src/build-x86_64-w64-mingw32/src“ wird verlassen
make[1]: *** [Makefile:552: all-recursive] Fehler 1
make[1]: Verzeichnis „/tmp/makepkg/mingw-w64-latexila/src/build-x86_64-w64-mingw32“ wird verlassen
make: *** [Makefile:482: all] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
```
Is this still related to the length of the directory?

**Comment by KrullKorg** [comment]
i updated it to 3.22.0 without problem using the command "BUILDDIR=/tmp makepkg-mingw -sLf"

#1939

**Comment by achadwick** [comment]
@aphirst 
You need to use `makepkg-mingw` to build. `BUILDDIR=/tmp` is probably a short enough name, no need for the nasty symlink hack.

**Comment by aphirst** [comment]
I changed the package version to 3.22.0 as @KrullKorg mentions, ran the same build command (now using `makepkg-mingw` as also suggested by @achadwick), and the build completed successfully, as did the installation. However, the application does nothing when run, simply quitting without any errors or output.

**Comment by lazka** [comment]
latexila was renamed to gnome-latex and updated multiple times in the meantime, so I guess this is fixed.
