### ISSUE TITLE
python3-cairo fails on import

### ISSUE THREAD

**Issue by tenko** [Alexpux/MINGW-packages#195]
Traceback:
```
Python 3.4.1 (default, Jul 15 2014, 16:49:38)
[GCC 4.9.0] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > import cairo
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "D:/msys64/mingw64/lib/python3.4/site-packages\cairo__init__.py", line 18, in <module>
> > >     from ._cairo import *
> > > UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 3: invalid start byte
> > > quit()
```

**Comment by eno93** [comment]
Same issue?

eno93@64-PC MSYS ~
$ python3
Python 3.4.3 (default, Jun 30 2015, 12:21:29)
[GCC 5.1.0] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cairo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.4/site-packages\cairo\__init__.py", line 18, in <module>
    from ._cairo import *
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 3: invalid start byte
>>> exit()

eno93@eno93-64-PC MSYS ~
$ pacman -Ss mingw-w64-python3-cairo-git

? No results

**Comment by Alexpux** [comment]
pacman -Ss python3-cairo-git

**Comment by eno93** [comment]
No result also :(

**Comment by Alexpux** [comment]
Ah, yeah. Git version is not buildable. You can to fix it yourself

**Comment by eno93** [comment]
Thank you anyway.

**Comment by darkf** [comment]
This is still an issue.

**Comment by achadwick** [comment]
Some sort of encoding issue? @lazka is getting "can't decode byte 0xec in position 5", the rest of us get the message above and below:

```
Python 3.5.2 (default, Nov  7 2016, 14:06:02)  [GCC 6.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cairo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.5/site-packages\cairo\__init__.py", line 18, in <module>
    from ._cairo import *
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 3: invalid start byte
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> sys.getfilesystemencoding()
'mbcs'
```

**Comment by achadwick** [comment]
I can confirm that the fixed `-git` package after #1994 doesn't suffer from this issue: `cairo` imports cleanly.

**Comment by lazka** [comment]
It imports here, but is empty. I think due to an absolute path being used for __init__.py in setup.py

**Comment by lazka** [comment]
ok, I have a fix. I'll work on a PR

**Comment by lazka** [comment]
See #2000 (note: this affects the non-git package only)

**Comment by lazka** [comment]
Does anyone care about the -git package? I can update the package there as well, but if the main package is enough I'd vote for removing the git one.

Either way, this can be closed afaics.

**Comment by elieux** [comment]
For the record, I see this with `mingw-w64-x86_64-python3-cairo`:
```
$ python3
Python 3.5.2 (default, Nov  7 2016, 14:06:02)  [GCC 6.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cairo
>>> dir(cairo)
['ANTIALIAS_DEFAULT', 'ANTIALIAS_GRAY', 'ANTIALIAS_NONE', 'ANTIALIAS_SUBPIXEL', 'CAPI', 'CONTENT_ALPHA', 'CONTENT_COLOR', 'CONTENT_COLOR_ALPHA', 'Context', 'EXTEND_NONE', 'EXTEND_PAD', 'EXTEND_REFLECT', 'EXTEND_REPEAT', 'FILL_RULE_EVEN_ODD', 'FILL_RULE_WINDING', 'FILTER_BEST', 'FILTER_BILINEAR', 'FILTER_FAST', 'FILTER_GAUSSIAN', 'FILTER_GOOD', 'FILTER_NEAREST', 'FONT_SLANT_ITALIC', 'FONT_SLANT_NORMAL', 'FONT_SLANT_OBLIQUE', 'FONT_WEIGHT_BOLD', 'FONT_WEIGHT_NORMAL', 'FORMAT_A1', 'FORMAT_A8', 'FORMAT_ARGB32', 'FORMAT_RGB16_565', 'FORMAT_RGB24', 'FontFace', 'FontOptions', 'Gradient', 'HAS_ATSUI_FONT', 'HAS_FT_FONT', 'HAS_GLITZ_SURFACE', 'HAS_IMAGE_SURFACE', 'HAS_PDF_SURFACE', 'HAS_PNG_FUNCTIONS', 'HAS_PS_SURFACE', 'HAS_QUARTZ_SURFACE', 'HAS_SVG_SURFACE', 'HAS_USER_FONT', 'HAS_WIN32_FONT', 'HAS_WIN32_SURFACE', 'HAS_XCB_SURFACE', 'HAS_XLIB_SURFACE', 'HINT_METRICS_DEFAULT', 'HINT_METRICS_OFF', 'HINT_METRICS_ON', 'HINT_STYLE_DEFAULT', 'HINT_STYLE_FULL', 'HINT_STYLE_MEDIUM', 'HINT_STYLE_NONE', 'HINT_STYLE_SLIGHT', 'ImageSurface', 'LINE_CAP_BUTT', 'LINE_CAP_ROUND', 'LINE_CAP_SQUARE', 'LINE_JOIN_BEVEL', 'LINE_JOIN_MITER', 'LINE_JOIN_ROUND', 'LinearGradient', 'Matrix', 'OPERATOR_ADD', 'OPERATOR_ATOP', 'OPERATOR_CLEAR', 'OPERATOR_DEST', 'OPERATOR_DEST_ATOP', 'OPERATOR_DEST_IN', 'OPERATOR_DEST_OUT', 'OPERATOR_DEST_OVER', 'OPERATOR_IN', 'OPERATOR_OUT', 'OPERATOR_OVER', 'OPERATOR_SATURATE', 'OPERATOR_SOURCE', 'OPERATOR_XOR', 'PATH_CLOSE_PATH', 'PATH_CURVE_TO', 'PATH_LINE_TO', 'PATH_MOVE_TO', 'PDFSurface', 'PSSurface', 'PS_LEVEL_2', 'PS_LEVEL_3', 'Pattern', 'RadialGradient', 'SUBPIXEL_ORDER_BGR', 'SUBPIXEL_ORDER_DEFAULT', 'SUBPIXEL_ORDER_RGB', 'SUBPIXEL_ORDER_VBGR', 'SUBPIXEL_ORDER_VRGB', 'SVGSurface', 'ScaledFont', 'SolidPattern', 'Surface', 'SurfacePattern', 'ToyFontFace', 'Win32PrintingSurface', 'Win32Surface', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_cairo', 'cairo_version', 'cairo_version_string', 'version', 'version_info']
>>> quit()
Error in atexit._run_exitfuncs:
OSError: [Errno -1] Windows Error 0xffffffff
```
