### ISSUE TITLE
MSYS2 Mingw64 does not compile correctly for JNI

### ISSUE THREAD

**Issue by kptlronyttcna** [Alexpux/MINGW-packages#1996]
I use this command `g++ Exercise3.cpp libprint.a -m64 -Wall -Wl,--add-stdcall-alias -shared -o Exercise3.dll -I "C:\Program Files\Java\jdk1.8.0_111\include" -I "C:\Program Files\Java\jdk1.8.0_111\include\win32"` in MSYS2 Mingw64 to generate my dll file, but when I run my java program it says 

`Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Ali\Desktop\Raymand\Exercise3\Exercise3.dll: %1 is not a valid Win32 application
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at Exercise3.main(Exercise3.java:5)`

However when I compile using TDM-GCC-64 with the same exact command everything works fine.

**Comment by dimztimz** [comment]
Probably libstdc++ dll fails to load. You need to put your dll and libstdc++ in same directory or add c:/msys64/mingw(32|64)/bin in your environment variable PATH before starting the Java. 

The thing with TDM-GCC is that it links statically by default with the standard library.
