### ISSUE TITLE
ipython color problem from mintty

### ISSUE THREAD

**Issue by chaffra** [Alexpux/MINGW-packages#2027]
With the lastest installed ipython(5.1) on mingw64, ipython is not showing colors nor doing autocompletion when running in the mintty shell. When double clicking on ipython2.cmd you can get all these features. Any help understanding why it's not working from the built-in shell is appreciated. Do I need to install pyreadline from pip or something?

**Comment by chaffra** [comment]
If I run ipython2 from start sh.exe --login -i then it works with all the features.

**Comment by chaffra** [comment]
I think the problem is that I used to be able to do

`winpty.exe  python2.exe /mingw64/bin/ipython2`. Now when I do that I am getting

```
Traceback (most recent call last):
  File "C:/msys64/mingw64/bin/ipython2", line 4, in <module>
    from IPython import start_ipython
  File "/mingw64/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <
module>
    from .core.application import Application
  File "/mingw64/lib/python2.7/site-packages/IPython/core/application.py", line
18, in <module>
    import logging
  File "/mingw64/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
ImportError: No module named time
```

**Comment by lazka** [comment]
Is this still a problem?

**Comment by lazka** [comment]
looks like ipython2 is broken in some other way atm:

```
$ ipython2
Traceback (most recent call last):
  File "C:/msys64/mingw64/bin/ipython2", line 4, in <module>
    from IPython import start_ipython
  File "C:/msys64/mingw64/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "C:/msys64/mingw64/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "C:/msys64/mingw64/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "C:/msys64/mingw64/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "C:/msys64/mingw64/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
```

**Comment by oltolm** [comment]
We have dropped support for Python 2, haven't we? It can probably be closed.
