### ISSUE TITLE
g-ir-scanner doesn't work with non-ascii home directory name

### ISSUE THREAD

**Issue by Forkest** [Alexpux/MINGW-packages#2088]
```
$ g-ir-scanner --namespace=n --library=l f
Traceback (most recent call last):
  File "C:/msys32/mingw32/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "C:/msys32/mingw32/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 527, in scanner_main
    transformer = create_transformer(namespace, options)
  File "C:/msys32/mingw32/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 383, in create_transformer
    symbol_filter_cmd=options.symbol_filter_cmd)
  File "C:/msys32/mingw32/bin/../lib/gobject-introspection/giscanner/transformer.py", line 54, in __init__
    self._cachestore = CacheStore()
  File "C:/msys32/mingw32/bin/../lib/gobject-introspection/giscanner/cachestore.py", line 60, in __init__
    self._directory = self._get_cachedir()
  File "C:/msys32/mingw32/bin/../lib/gobject-introspection/giscanner/cachestore.py", line 67, in _get_cachedir
    cachedir = utils.get_user_cache_dir('g-ir-scanner')
  File "C:/msys32/mingw32/bin/../lib/gobject-introspection/giscanner/utils.py", line 317, in get_user_cache_dir
    homedir = os.path.expanduser('~')
  File "C:/msys32/mingw32/lib/python2.7/ntpath.py", line 324, in expanduser
    return userhome + path[i:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 24: ordinal not in range(128)
```

Interesting enough, this works: `python -c "import os; print os.path.expanduser('~')"`

I have a bit obsolete msys, since I'm on XP, maybe it's already fixed, try it.

A workaround is to run `/usr/bin/mkpasswd > /etc/passwd` and change the home folder name there.

**Comment by lazka** [comment]
the utils.py has unicode_literals enabled, so an equivalent would be ``python -c "import os; print os.path.expanduser(u'~')"``

expanduser in Python 2 can't handle unicode paths on Windows and uses the old ANSI API so even if it wouldn't crash it would return a wrong result.

**Comment by lazka** [comment]
Moving gobject-introspection to Python 3 (it supports both, but Python 3 is not tested on Windows..), should fix this issue.

**Comment by lazka** [comment]
This should be fixed now with "1.54.1-3", which switched to Python 3.

**Comment by Forkest** [comment]
There was also [a workaround](https://stackoverflow.com/questions/23888120/an-alternative-to-os-path-expanduser) of unknown reliability for Python 2, leaving the link here just in case.

**Comment by lazka** [comment]
I just noticed that Python 3 might not support WinXP anymore, so not sure if this is an improvement for you all in all :/

**Comment by Forkest** [comment]
Yup, it doesn't, so I can't test whether it works now.
But I've used the workaround with renaming home folder name in passwd, so it doesn't bother me anymore. Good to have it fixed for other people, though.
