### ISSUE TITLE
g-ir-scanner doesn't work, path conversion problem

### ISSUE THREAD

**Issue by Forkest** [Alexpux/MINGW-packages#2198]
```
$ g-ir-scanner /dev/null --namespace=null --library=/dev/null --pkg glib-2.0
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
...
$ echo $PKG_CONFIG_PATH
/mingw32/lib/pkgconfig:/mingw32/share/pkgconfig
```

To debug this, I changed line 294 in `\mingw32\lib\gobject-introspection\giscanner\scannermain.py` to:
```
    args = [os.environ.get('PKG_CONFIG', 'pkg-config'), '--debug', '--exists', '--cflags']
```
Then the full output is:
```
$ g-ir-scanner /dev/null --namespace=null --library=/dev/null --pkg glib-2.0
Ignoring incompatible output option "--cflags"
Error printing disabled by default due to use of output options --exists, --atleast/exact/max-version, --list-all or no output option at all. Value of --print-errors: 0
Error printing disabled
Adding virtual 'pkg-config' package to list of known packages
Cannot open directory #1 'C' in package search path: No such file or directory
Cannot open directory #2 '\msys2\mingw32\lib\pkgconfig;C' in package search path: No such file or directory
Scanning directory #3 '\msys2\mingw32\share\pkgconfig'
File 'formw.pc' appears to be a .pc file
Will find package 'formw' in file '\msys2\mingw32\share\pkgconfig/formw.pc'
File 'menuw.pc' appears to be a .pc file
Will find package 'menuw' in file '\msys2\mingw32\share\pkgconfig/menuw.pc'
File 'ncurses++w.pc' appears to be a .pc file
Will find package 'ncurses++w' in file '\msys2\mingw32\share\pkgconfig/ncurses++w.pc'
File 'ncursesw.pc' appears to be a .pc file
Will find package 'ncursesw' in file '\msys2\mingw32\share\pkgconfig/ncursesw.pc'
File 'panelw.pc' appears to be a .pc file
Will find package 'panelw' in file '\msys2\mingw32\share\pkgconfig/panelw.pc'
File 'shared-mime-info.pc' appears to be a .pc file
Will find package 'shared-mime-info' in file '\msys2\mingw32\share\pkgconfig/shared-mime-info.pc'
Scanning directory #4 '/usr/lib/pkgconfig'
File 'bash-completion.pc' appears to be a .pc file
Will find package 'bash-completion' in file '/usr/lib/pkgconfig/bash-completion.pc'
File 'libalpm.pc' appears to be a .pc file
Will find package 'libalpm' in file '/usr/lib/pkgconfig/libalpm.pc'
Cannot open directory #5 '/usr/share/pkgconfig' in package search path: No such file or directory
Looking for package 'glib-2.0'
Looking for package 'glib-2.0-uninstalled'
Package gio-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gio-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gio-2.0' found
Package gmodule-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gmodule-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gmodule-2.0' found
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
C:/msys2/build/openwebrtc-0.3.0/owr/tmp-introspectdmkysl/null-None.c:2:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
Traceback (most recent call last):
  File "C:/msys2/mingw32/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "C:/msys2/mingw32/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 549, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "C:/msys2/mingw32/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 423, in create_binary
    gdump_parser.get_error_quark_functions())
  File "C:/msys2/mingw32/bin/../lib/gobject-introspection/giscanner/dumper.py", line 328, in compile_introspection_binary
    return dc.run()
  File "C:/msys2/mingw32/bin/../lib/gobject-introspection/giscanner/dumper.py", line 167, in run
    introspection_obj = self._compile(c_path)
  File "C:/msys2/mingw32/bin/../lib/gobject-introspection/giscanner/dumper.py", line 207, in _compile
    self._options.init_sections)
  File "C:/msys2/mingw32/bin/../lib/gobject-introspection/giscanner/ccompiler.py", line 241, in compile
    source_str.rfind(os.sep)]))
  File "C:/msys2/mingw32/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "C:/msys2/mingw32/lib/python2.7/distutils/cygwinccompiler.py", line 189, in _compile
    raise CompileError, msg
distutils.errors.CompileError: command 'C:\\msys2\\mingw32\\bin/i686-w64-mingw32-gcc.exe' failed with exit status 1
```

As you can easily see from the first lines of ouput, it is a problem with path conversion:
```
Cannot open directory #1 'C' in package search path: No such file or directory
Cannot open directory #2 '\msys2\mingw32\lib\pkgconfig;C' in package search path: No such file or directory
Scanning directory #3 '\msys2\mingw32\share\pkgconfig'
```

**Comment by Forkest** [comment]
Have I reported this in the right repository? Which layer of MSYS is responsible for this kind of path translation?

**Comment by mati865** [comment]
Maybe you don't have `mingw-w64-i686-glib2` installed:
```
$ g-ir-scanner /dev/null --namespace=null --library=/dev/null --pkg glib-2.0
./nul.dll.a: file not recognized: File truncated
collect2.exe: error: ld returned 1 exit status
Traceback (most recent call last):
  File "D:/msys64/mingw32/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "D:/msys64/mingw32/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 545, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "D:/msys64/mingw32/bin/../lib/gobject-introspection/giscanner/scannermain.py", line 419, in create_binary
    gdump_parser.get_error_quark_functions())
  File "D:/msys64/mingw32/bin/../lib/gobject-introspection/giscanner/dumper.py", line 328, in compile_introspection_binary
    return dc.run()
  File "D:/msys64/mingw32/bin/../lib/gobject-introspection/giscanner/dumper.py", line 174, in run
    self._link(bin_path, introspection_obj)
  File "D:/msys64/mingw32/bin/../lib/gobject-introspection/giscanner/dumper.py", line 296, in _link
    raise LinkError(e)
distutils.errors.LinkError: command 'D:\\msys64\\mingw32\\bin/i686-w64-mingw32-gcc.exe' failed with exit status 1
```

**Comment by Forkest** [comment]
Interesting, so it works for you. I'm using a bit outdated MSYS since I'm on XP and the support for it was dropped recently, maybe that's the problem. I should retest it on a modern OS with the latest MSYS.

glib was just an example, it is available. pkg-config call directly from MSYS console works fine, only through g-ir-scanner it fails. The problem is with PKG_CONFIG_PATH mangling.

**Comment by lazka** [comment]
Maybe this is due to the msys pkg-config being used instead of the mingw one? `which pkg-config` ?

**Comment by Forkest** [comment]
@lazka, you are right, mingw version of pkg-config wasn't installed. Solved, thanks!

Maybe add mingw pkg-config as a dependency for gobject-introspection?

**Comment by lazka** [comment]
> @lazka, you are right, mingw version of pkg-config wasn't installed. Solved, thanks!

cool :)

> Maybe add mingw pkg-config as a dependency for gobject-introspection?

Good idea.
