### ISSUE TITLE
libgcrypt: checks are failing

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MINGW-packages#2460]
When I was testing `xmlsec `package, I have realized that some of the test were failing there, even some of them with SIGSEGV.
I have debugged it and it seems that it is not in `xmlsec`, but when it calls the underlying `libgcrypt`, to be specific [here](https://github.com/lsh123/xmlsec/blob/master/src/gcrypt/asymkeys.c#L280)

Then I have built locally `libgcrypt`, and run `make check`, which revealed that many tests are actually failing:
```
PASS: version.exe
FAIL: mpitests.exe
PASS: t-sexp.exe
PASS: t-convert.exe
FAIL: t-mpi-bit.exe
FAIL: t-mpi-point.exe
FAIL: curves.exe
PASS: t-lock.exe
FAIL: prime.exe
FAIL: basic.exe
/bin/sh: line 5: 48560 Segmentation fault      GCRYPT_IN_REGRESSION_TEST=1 ${dir}$tst
FAIL: keygen.exe
FAIL: pubkey.exe
```
Anybody who is more familiar with `libgcrypt  `library could look at these tests coming with `libgcrypt `and decide whether these are MINGW specific issues or the upstream team should be notified?

**Comment by peterbud** [comment]
More info with bt:
```
#0  0x0000000065482fe8 in free () from C:\Development\msys64\dbg\bin\libgcrypt-20.dll
#1  0x00000000653c5075 in _gcry_free (p=0x163fd0) at global.c:893
#2  0x000000006547b912 in _gcry_mpi_print (format=format@entry=GCRYMPI_FMT_HEX, buffer=buffer@entry=0x0, buflen=buflen@entry=0, nwritten=nwritten@entry=0x67fd38, a=a@entry=0x163f10) at mpicoder.c:849
#3  0x000000006547b9b3 in _gcry_mpi_aprint (format=format@entry=GCRYMPI_FMT_HEX, buffer=buffer@entry=0x67fe08, nwritten=nwritten@entry=0x0, a=a@entry=0x163f10) at mpicoder.c:871
#4  0x00000000653c1999 in gcry_mpi_aprint (format=format@entry=GCRYMPI_FMT_HEX, buffer=buffer@entry=0x67fe08, nwritten=nwritten@entry=0x0, a=a@entry=0x163f10) at visibility.c:374
#5  0x000000000040396b in test_add () at mpitests.c:395
#6  main (argc=<optimized out>, argv=<optimized out>) at mpitests.c:610
```

**Comment by peterbud** [comment]
Reported the bug upstream: [https://dev.gnupg.org/T3184](https://dev.gnupg.org/T3184)
Looks like a file is missing from the official tarball
