### ISSUE TITLE
python3 scipy does not work, DLL load error in scipy.special

### ISSUE THREAD

**Issue by agrechnev** [Alexpux/MINGW-packages#3108]
Packages installed (Windows 10-64, msys2+mingw_w64):
mingw64/mingw-w64-x86_64-python3-scipy 0.19.0-1
mingw64/mingw-w64-x86_64-python3-numpy 1.13.0-1
mingw64/mingw-w64-x86_64-python3 3.6.3-1

When I try to import scipy.signal (or pretty much any scipy subpackage), I get the error:
 import scipy.signal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\msys64\mingw64\lib\python3.6\site-packages\scipy\signal\__init__.py", line 304, in <module>
    from .bsplines import *
  File "D:\msys64\mingw64\lib\python3.6\site-packages\scipy\signal\bsplines.py", line 12, in <module>
    from scipy.special import comb, gamma
  File "D:\msys64\mingw64\lib\python3.6\site-packages\scipy\special\__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified procedure could not be found.

mingw32 version gives exactly the same error (on a different PC). 

Dependency Walker shows that _ufuncs-cpython-36m.dll is missing libgfortran-3.dll, but fixing this (by copying libgfortran-4.dll as libgfortran-3.dll) does not change anything.

**Comment by lazka** [comment]
scipy has been updated/rebuild two days ago, can you update and check again?

https://quodlibet.duckdns.org/msys2/package/mingw-w64-i686-python3-scipy

**Comment by agrechnev** [comment]
It works now, thanks.
