### ISSUE TITLE
g-ir-scanner not working with poppler and pango

### ISSUE THREAD

**Issue by dsisnero** [Alexpux/MINGW-packages#3122]
g-ir-scanner -V
Traceback (most recent call last):
  File "C:\Dominic\tools\msys64\mingw64\bin\g-ir-scanner-script.py", line 65, in <module>
    from giscanner.scannermain import scanner_main
  File "C:\Dominic\tools\msys64\mingw64\bin/../lib/gobject-introspection/giscanner/scannermain.py", line 41, in <module>
    from giscanner.dumper import compile_introspection_binary
  File "C:\Dominic\tools\msys64\mingw64\bin/../lib/gobject-introspection/giscanner/dumper.py", line 35, in <module>
    from .gdumpparser import IntrospectionBinary
  File "C:\Dominic\tools\msys64\mingw64\bin/../lib/gobject-introspection/giscanner/gdumpparser.py", line 37, in <module>
    from .transformer import TransformerException
  File "C:\Dominic\tools\msys64\mingw64\bin/../lib/gobject-introspection/giscanner/transformer.py", line 34, in <module>
    from .girparser import GIRParser
  File "C:\Dominic\tools\msys64\mingw64\bin/../lib/gobject-introspection/giscanner/girparser.py", line 31, in <module>
    from .girwriter import COMPATIBLE_GIR_VERSION
  File "C:\Dominic\tools\msys64\mingw64\bin/../lib/gobject-introspection/giscanner/girwriter.py", line 29, in <module>
    from .xmlwriter import XMLWriter
  File "C:\Dominic\tools\msys64\mingw64\bin/../lib/gobject-introspection/giscanner/xmlwriter.py", line 46, in <module>
    from giscanner._giscanner import collect_attributes
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by lazka** [comment]
Does updating everything with "pacman -Suy" help?

**Comment by revelator** [comment]
Unfortunatly no.

**Comment by revelator** [comment]
Update: 
It works on some packages, poppler and pango fails besides a few others.

**Comment by lazka** [comment]
I also had crashes in g-ir-scanner for pango recently, but not with the error mentioned here.

**Comment by revelator** [comment]
Had to rebuild glib2 before the executable not found error went away, still fails on pango with a rather long error something like returned non zero exit status -1246457567.  not sure why since i got it from server when updating, but something might have locked it so the update failed. 

It only seems to affect some packages so it might be an upstream bug since i see people on linux also have trouble with introspection.

**Comment by lazka** [comment]
That's the same issue I see with pango, the binary it creates for introspection crashes when executing.

**Comment by revelator** [comment]
So it would seem yes. 
need to figure out why and where then, ill see if i can get some dumps for gdb to look at.

**Comment by lazka** [comment]
When I looked a bit into this some time ago, the first thing I learned was that setting GI_SCANNER_DEBUG=save-temps keeps the binaries around, maybe that helps.

**Comment by revelator** [comment]
Aye that should do the trick, ill see if i can get anything usefull out of it.

**Comment by lazka** [comment]
Wild guess, maybe it's linking against the system lib instead of the  building one and uninstalling pango before building it might help?

**Comment by lazka** [comment]
Uniscribe docs: "Important  Starting with Windows 8: To maintain the ability to run on Windows 7, a module that uses Uniscribe must specify Usp10.lib before gdi32.lib in its library list."

**Comment by lazka** [comment]
I've opened #3556  and #3559 for both issues.

**Comment by lazka** [comment]
Should be fixed
