### ISSUE TITLE
Cannot install pygraphviz with pip3

### ISSUE THREAD

**Issue by ArekPiekarz** [Alexpux/MINGW-packages#3322]
Trying to install pygrapviz with pip3 x64 fails with a following error:

```
File "D:/app/msys64/mingw64/lib/python3.6\distutils\ccompiler.py", line 1091, in gen_lib_options
    lib_opts.append(compiler.library_dir_option(dir))
File "D:/app/msys64/mingw64/lib/python3.6\distutils\unixccompiler.py", line 207, in library_dir_option
    return "-L" + dir
TypeError: must be str, not NoneType
```

Note that you also have to `pacboy sync graphviz:x` to get to that stage of installation.

Full log:

```
$ pip3 install pygraphviz
Collecting pygraphviz
  Downloading pygraphviz-1.3.1.zip (123kB)
    100% |################################| 133kB 1.4MB/s
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz ... error
    Complete output from command D:/app/msys64/mingw64/bin/python3.exe -u -c "import setuptools, tokenize;__file__='C:/Users/Fazer/AppData/Local/Temp/pip-build-shl0io
yr/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --rec
ord C:/Users/Fazer/AppData/Local/Temp/pip-q6wup0k6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    include_dirs=None
    library_dirs=None
    running build
    running build_py
    creating build
    creating build/lib.mingw-3.6
    creating build/lib.mingw-3.6/pygraphviz
    copying pygraphviz/agraph.py -> build/lib.mingw-3.6/pygraphviz
    copying pygraphviz/graphviz.py -> build/lib.mingw-3.6/pygraphviz
    copying pygraphviz/release.py -> build/lib.mingw-3.6/pygraphviz
    copying pygraphviz/version.py -> build/lib.mingw-3.6/pygraphviz
    copying pygraphviz/__init__.py -> build/lib.mingw-3.6/pygraphviz
    creating build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_attributes.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_attribute_defaults.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_clear.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_drawing.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_edge_attributes.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_graph.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_html.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_layout.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_node_attributes.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_readwrite.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_string.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_subgraph.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/test_unicode.py -> build/lib.mingw-3.6/pygraphviz/tests
    copying pygraphviz/tests/__init__.py -> build/lib.mingw-3.6/pygraphviz/tests
    running egg_info
    writing pygraphviz.egg-info/PKG-INFO
    writing dependency_links to pygraphviz.egg-info/dependency_links.txt
    writing top-level names to pygraphviz.egg-info/top_level.txt
    reading manifest file 'pygraphviz.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc/build'
    writing manifest file 'pygraphviz.egg-info/SOURCES.txt'
    copying pygraphviz/graphviz.i -> build/lib.mingw-3.6/pygraphviz
    copying pygraphviz/graphviz_wrap.c -> build/lib.mingw-3.6/pygraphviz
    running build_ext
    building 'pygraphviz._graphviz' extension
    creating build/temp.mingw-3.6
    creating build/temp.mingw-3.6/pygraphviz
    D:\app\msys64\mingw64\bin/x86_64-w64-mingw32-gcc.exe -Wno-unused-result -Wsign-compare -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_                                                                       STDIO=1 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -DNDEBUG -INone -ID:/app/msys64/mingw64/include/python3.6m -c pygraphviz/gr                                                                       aphviz_wrap.c -o build/temp.mingw-3.6/pygraphviz/graphviz_wrap.o
    pygraphviz/graphviz_wrap.c: In function 'agattr_label':
    pygraphviz/graphviz_wrap.c:3321:12: warning: return makes integer from pointer without a cast [-Wint-conversion]
         return agattr(g, kind, name, val);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
    writing build/temp.mingw-3.6/pygraphviz/_graphviz-cpython-36m.def
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:/Users/Fazer/AppData/Local/Temp/pip-build-shl0ioyr/pygraphviz/setup.py", line 87, in <module>
        tests_require=['nose>=0.10.1', 'doctest-ignore-unicode>=0.1.0',],
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:/Users/Fazer/AppData/Local/Temp/pip-build-shl0ioyr/pygraphviz\setup_commands.py", line 50, in modified_run
        orig_run(self)
      File "D:/app/msys64/mingw64/lib/python3.6/site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:/app/msys64/mingw64/lib/python3.6/site-packages\setuptools\command\build_ext.py", line 75, in run
        _build_ext.run(self)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "D:/app/msys64/mingw64/lib/python3.6/site-packages\setuptools\command\build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\command\build_ext.py", line 559, in build_extension
        target_lang=language)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\ccompiler.py", line 717, in link_shared_object
        extra_preargs, extra_postargs, build_temp, target_lang)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\cygwinccompiler.py", line 249, in link
        target_lang)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\unixccompiler.py", line 159, in link
        libraries)
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\ccompiler.py", line 1091, in gen_lib_options
        lib_opts.append(compiler.library_dir_option(dir))
      File "D:/app/msys64/mingw64/lib/python3.6\distutils\unixccompiler.py", line 207, in library_dir_option
        return "-L" + dir
    TypeError: must be str, not NoneType

    ----------------------------------------
Command "D:/app/msys64/mingw64/bin/python3.exe -u -c "import setuptools, tokenize;__file__='C:/Users/Fazer/AppData/Local/Temp/pip-build-shl0ioyr/pygraphviz/setup.py';
f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:/Users/Fazer/AppDa
ta/Local/Temp/pip-q6wup0k6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:/Users/Fazer/AppData/Local/Temp/pip-
build-shl0ioyr/pygraphviz/
```

**Comment by Alexpux** [comment]
Ming’s python is not official and have some incompatibilities with MSVC one. You need fix pygraphviz sources to be able install it.
Feel free to create package for it with fixes
