### ISSUE TITLE
python2 - problem with library search order?

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#3343]
We found [an issue downstream](https://bugs.launchpad.net/inkscape/+bug/1746092) where Python searches for libraries of a dynamically linked module (_hashlib.pyd) in an order that makes it likely to cause problems:

_hashlib.pyd is linked against LIBEAY32.dll; when loaded it attempts to load
```
C:\Program Files\Inkscape\lib\python2.7\LIBEAY32.dll
C:\Windows\System32\LIBEAY32.dll
C:\Windows\System\LIBEAY32.dll
C:\Windows\LIBEAY32.dll
C:\Program Files\Inkscape\libeay32.dll
```

This is consistent with what is described at
https://github.com/numpy/numpy/wiki/windows-dll-notes

Unfortunately if an incompatible LIBEAY32.dll (or any other DLL that needs to be loaded) is found in one of the system directories the module load fails.

There are easy steps to reproduce this:
* Create an empty file at C:\Windows\System32\LIBEAY32.dll
* Open cmd.exe
* Launch C:\msys64\mingw64\bin\python.exe
* Execute "import hashlib"
* See errors like
```
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:\msys64\mingw64\lib\python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
```

I've found that this does not seem to happen when launched from inside an MSYS2 shell (anybody knows what is different in this scenario?).

A workaround for Inkscape seems to be to call [SetDllDirectory](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686203.aspx) but for standalone Python that still won't work.

Any ideas what is going wrong and how/where to fix it best? Interestingly python3.6.exe is not afdfected either, so maybe there is already a solution available?

**Comment by lazka** [comment]
Weird, I can reproduce with mingw64 but not with mingw32.

**Comment by Ede123** [comment]
Indeed! Only happens with mingw64 for me, too.

**Comment by mingwandroid** [comment]
You'd need to put the broken DLL in syswow64 for 32 bit. This is just
standard DLL-hell though, no one but Microsoft should put libraries in that
folder and the software doing this is broken and inconsiderate. On Python 3
hashlib depends on openssl much less (if at all).

**Comment by lazka** [comment]
@mingwandroid ah, thanks. Shouldn't python still prefer the DLL in the directory of the python.exe?

**Comment by mingwandroid** [comment]
@lazka, well, the code to load an extension module is here:

https://github.com/python/cpython/blob/f7eae0adfcd4c50034281b2c69f461b43b68db84/Python/dynload_win.c#L218-L222

```
        /* We use LoadLibraryEx so Windows looks for dependent DLLs
            in directory of pathname first. */
        /* XXX This call doesn't exist in Windows CE */
        hDLL = LoadLibraryExW(wpathname, NULL,
                              LOAD_WITH_ALTERED_SEARCH_PATH);
```

So `LOAD_WITH_ALTERED_SEARCH_PATH` causes the Windows loader to look not in the folder containing `python*.exe` but in the `dyn-load` folder instead. It would be nice if it looked in this folder first, but that does not seem to be the case. Search for `Alternate Search Order for Desktop Applications` on:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx

**Comment by lazka** [comment]
Thanks @mingwandroid . Makes sense, and the order you mentioned would indeed be nicer.

From what I see you can get that order by combining LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR and LOAD_LIBRARY_SEARCH_DEFAULT_DIRS, but those are only available with Windows 7.

**Comment by mingwandroid** [comment]
Ah ok, good research. We could think to add the executable's dirname to the dll search path somewhere around Python_Init. Am on my phone so cannot find the correct function names ATM!

**Comment by lazka** [comment]
Yeah, if the numpy wiki is correct, then
```
if (GetProcAddress(GetModuleHandleW(L"kernel32.dll"), "SetDefaultDllDirectories"))
    SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_DEFAULT_DIRS);
```

in init might work.

> Experiments suggest that, if you first set DLL search order with LOAD_LIBRARY_SEARCH_* flags to SetDefaultDllDiectories, then call LoadLibraryEx with LOAD_WITH_ALTERED_SEARCH_PATH, then the load-dll path will be prefixed to the search order given by your LOAD_LIBRARY_SEARCH_* flags.

Now I also understand why MSYS2 Python always prepends the executable directory to PATH while the official Python doesn't.  Otherwise nothing would be found...

**Comment by Ede123** [comment]
What about simply using [SetDllDirectory](https://msdn.microsoft.com/library/windows/desktop/ms686203.aspx) and point it to the /bin folder (i.e. where python executable is located)? 

It seems to work even when python is spawned as a child process by Inkscape, so should be fine for python itself, too, or am I overlooking any edge cases?

**Comment by lazka** [comment]
As long as SetDllDirectory does not undo the effect of LOAD_WITH_ALTERED_SEARCH_PATH, then that sounds more reliable.

**Comment by lazka** [comment]
To verify that put the empty LIBEAY32.dll into "/mingw64/lib/python2.7/lib-dynload/" and it should fail despite of SetDllDirectory.

**Comment by Ede123** [comment]
Ah, that might be a problem...
I think https://msdn.microsoft.com/library/windows/desktop/ms682586.aspx#alternate_search_order_for_desktop_applications describes the modes in question - according to this SetDllDirectory activates an alternate search order, too, but it differs from what LOAD_WITH_ALTERED_SEARCH_PATH achieves (notably by omitting "The directory specified by lpFileName.", i.e. the name of the DLL loaded by LoadLibraryEx).

**Comment by Ede123** [comment]
Behavior with SetDllDirectory confirmed. Search order is
```
C:\Program Files\Inkscape\lib\python2.7\LIBEAY32.dll
C:\Program Files\Inkscape\libeay32.dll
```
(i.e. SetDllDirectory in second place and "The directory from which the application loaded" in first place as documented)

On a side note: In all those cases I wonder how "C:\Program Files\Inkscape\lib\python2.7" is the first directory searched? It does contain neither the python.exe nor the _hashlib.pyd.

**Comment by lazka** [comment]
small note: that it searches first in bin seems to be some MSYS patching, starting python with "MSYSTEM= python" makes it search in lib first, but also in lib\python2.7 and not lib-dynload as you noted.

**Comment by Ede123** [comment]
Seems python3 is affected, too, see #3381.

Interestingly python3 does try to search in "lib-dynload/" so there seems to be a slight difference here.

Did we reach a consensus on what the best solution might be?
* I'm still unsure wether "SetDllDirectory" might have any undesired side effects by excluding the path the .dll was loaded from. Probably not for most packages but who knows if some extensions ship their dependencies in the module directory?
* A combination of  `LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR` and `LOAD_LIBRARY_SEARCH_DEFAULT_DIRS` as suggested by @lazka initially therefore does indeed sound more suitable but if I understand correctly this does then disable searching on the PATH (which in turn might cause yet other problems)?.
* Do we have another possibility I overlooked?

Any thoughts?

**Comment by lazka** [comment]
Some related recent upstream changes for 3.8: https://github.com/python/cpython/commit/2438cdf0e932a341c7613bf4323d06b91ae9f1f1
