### ISSUE TITLE
python3 unable to import ssl module

### ISSUE THREAD

**Issue by dsorber** [Alexpux/MINGW-packages#3381]
With a fresh install of MSYS2 and `mingw-w64-x86_64-python3` I cannot import the ssl module.  This prevents `pip3` and other tools from working correctly.

```
$ python3
Python 3.6.4 (default, Jan 23 2018, 13:17:37)  [GCC 7.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.6\ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified procedure could not be found.
>>>
```

The .dll appears to be in the correct place, I'm not sure what's wrong:

```
$ ls -l /mingw64/lib/python3.6/lib-dynload/_ssl-cpython-36m.dll
-rwxr-xr-x 1 dsorber Domain Users 96256 Jan 23 05:21 /mingw64/lib/python3.6/lib-dynload/_ssl-cpython-36m.dll
```

I also installed `mingw-w64-x86_64-openssl` and `mingw-w64-x86_64-libressl` but they had no effect.

**Comment by Alexpux** [comment]
@dsorber It works for me. See that you don't have some similar programs or libraries in the PATH

**Comment by dsorber** [comment]
I'm not sure what you mean...

```
$ which python3
/mingw64/bin/python3
```

```
$ /mingw64/bin/python3
Python 3.6.4 (default, Jan 23 2018, 13:17:37)  [GCC 7.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.6\ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified procedure could not be found.
>>>
```
As I said above, I just did a fresh install to confirm. The only things I've installed are the three packages mentioned.

**Comment by Alexpux** [comment]
I mean maybe you have OpenSSL libraries in the PATH that python picked instead mingw64

**Comment by dsorber** [comment]
I don't have OpenSSL installed anywhere else in my PATH.  Does this work for you with a clean install?

**Comment by Alexpux** [comment]
I don’t have clean installs and can’t test it

**Comment by Ede123** [comment]
You could check if it is something related to #3343.

[Process Monitor](https://technet.microsoft.com/sysinternals/processmonitor.aspx) has proved itself to be very helpful to check which DLLs Python is attempting to load, so it should also tell you if Python is loading a wrong library.

**Comment by dsorber** [comment]
@Ede123 Thanks very much for the hint! It appears to be much the same problem as in #3343.

Process Monitor shows that `python3.exe` is attempting to load `C:\msys64\mingw64\lib\python3.6\lib-dynload\LIBEAY32.dll` and `C:\msys64\mingw64\lib\python3.6\lib-dynload\SSLEAY32.dll` which don't exist because they both live in `C:\msys64\mingw64\bin`.   python3.exe then attempts to load the wrong versions of those .dlls from `C:\Windows\System32\`, leading the error I saw.

I'm not sure what the correct solution is but I temporarily copied both .dll's to `C:\msys64\mingw64\lib\python3.6\lib-dynload\` and now `import ssl` works correctly.

Thanks again, I've been stuck on this for too long.

**Comment by Ede123** [comment]
Interesting... In the other bug we were wondering why Python did *not* attempt to load DLLs from `lib-dynload/` - seems python3 behaves differently here. Aside from that it indeed does sound like the same issue, though.

**Comment by lazka** [comment]
hm, could the .dll come from the new openssh client in Windows 10?

**Comment by dsorber** [comment]
I don't think so; I forgot to mention above but this was all on Windows 7.
