### ISSUE TITLE
meld: 'gi.repository.PangoCairo' object has no attribute 'Win32FontMap'

### ISSUE THREAD

**Issue by fabiangreffrath** [Alexpux/MINGW-packages#3610]
Hi there,

after today's upgrade, meld refuses to start:
```
Traceback (most recent call last):
  File "D:/msys32/mingw32/bin/meld", line 367, in <module>
    PangoCairo.FontMap.set_default(PangoCairo.Win32FontMap())
  File "D:/msys32/mingw32/lib/python3.6/site-packages\gi\module.py", line 138, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.PangoCairo' object has no attribute 'Win32FontMap'
```

**Comment by lazka** [comment]
likely due to the pango switch to meson, I'll have a look.

**Comment by lazka** [comment]
oh, I see meld was updated as well

**Comment by lazka** [comment]
I've opened #3611

**Comment by fabiangreffrath** [comment]
Impressive, thank you!
