### ISSUE TITLE
Python 3.7.0 scipy curve_fit failed loading

### ISSUE THREAD

**Issue by xiaowen64** [Alexpux/MINGW-packages#4152]
Python 3.7.0 (default, Aug 3 2018, 11:56:18) [GCC 8.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
'>>>' from scipy.optimize import curve_fit
Traceback (most recent call last):
File "", line 1, in 
File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\optimize_init_.py", line 271, in 
from .minimize import *
File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\optimize_minimize.py", line 21, in 
from scipy.sparse.linalg import LinearOperator
File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\sparse\linalg_init.py", line 117, in 
from .eigen import *
File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\sparse\linalg\eigen_init_.py", line 11, in 
from .arpack import *
File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\sparse\linalg\eigen\arpack_init_.py", line 22, in 
from .arpack import *
File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in 
from . import _arpack
ImportError: DLL load failed: The specified module could not be found.

**Comment by Alexpux** [comment]
I’m upload new aepack package. Is it not solve issue?

**Comment by xiaowen64** [comment]
apparently not.
