### ISSUE TITLE
Use Azure Pipelines for CI

### ISSUE THREAD

**Issue by lazka** [Alexpux/MINGW-packages#4396]
https://azure.microsoft.com/en-us/services/devops/pipelines/

tl;dr; 10 parallel builds, 6 hours max build time per job, Server 2012/2016

I've played around a bit with it here: ~https://github.com/lazka/msys2-azure-pipelines~

This just installs MSYS2 and installs the toolchain in two parallel jobs: ~https://dev.azure.com/lazka/test/_build/results?buildId=17&view=logs~

This is how a PR looks like: ~https://github.com/lazka/msys2-azure-pipelines/pull/1~

**Comment by Ede123** [comment]
Sounds interesting (although bloated), especially as they claim to offer builds for Mac, Linux and Windows at the same time.

Is there a possibility to publicly display the build logs without owning a Microsoft account? Every link I found produces a login page, which is not particularly helpful for open source projects...

**Comment by lazka** [comment]
> Sounds interesting (although bloated), especially as they claim to offer builds for Mac, Linux and Windows at the same time.

appveyor also does windows+linux (but yeah, it's enterprisey..)

> Is there a possibility to publicly display the build logs without owning a Microsoft account? Every link I found produces a login page, which is not particularly helpful for open source projects...

Good point. In the end they just redirect to a public page, not sure if that is intentional...

**Comment by lazka** [comment]
> > Is there a possibility to publicly display the build logs without owning a Microsoft account? Every link I found produces a login page, which is not particularly helpful for open source projects...
> 
> Good point. In the end they just redirect to a public page, not sure if that is intentional...

Does this work for you https://github.com/lazka/MINGW-packages/pull/1 ?

**Comment by Ede123** [comment]
Yes, I can access the logs for the individual build steps without signing in:
![grafik](https://user-images.githubusercontent.com/904570/45483922-a8ae5a00-b752-11e8-8ce3-f78264f22d60.png)

**Comment by lazka** [comment]
Cool, seems the login is only a thing when you add it through the github marketplace.

**Comment by lazka** [comment]
ok, I need rights to add web hooks: "Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository." :(

**Comment by lazka** [comment]
@Alexpux I've send you an email invite. Please go to https://dev.azure.com/msys2/mingw/_build -> "GitHub" -> "New pipeline" -> "Authorize with OAuth" -> Select this git repo -> ...

**Comment by peterbud** [comment]
@lazka  - I cannot access the log... When I click on the highlighted link, it tries to authorize me and fails

![image](https://user-images.githubusercontent.com/7863452/45560712-33bc4c80-b846-11e8-8f9c-bf04b8abc518.png)

**Comment by lazka** [comment]
@peterbud I've already removed the azure projects for all test repos.

But I've moved quodlibet to it, you can try there: https://github.com/quodlibet/quodlibet/commits/master

**Comment by edglas1** [comment]
@lazka, I'm on the azure devops pipelines team and can help you out. The project you created must be marked as a public project to get rid of the 401s. Go to Project Settings | Overview and set the Visibility to Public.
https://dev.azure.com/lazka/test/_settings/projectOverview

**Comment by lazka** [comment]
Thanks @edglas1. It all works fine, I deleted the (test)project already which is why the links are broken :)

**Comment by edglas1** [comment]
Ok glad you got it working. We are rolling out a fix today for the github app issue (it is almost completely rolled out now). Sorry for the hassle there. Any feedback based on your experience so far?

**Comment by lazka** [comment]
> Any feedback based on your experience so far?

It was confusing that when you set it up the trigger config is by default overridden through the web UI and it doesn't trigger for all branches by default. It would be nice if it would just default to all branches and not ignore the yaml config initially.

Other than that works & looks great so far.

**Comment by edglas1** [comment]
Ok thanks that's good feedback. We were just discussing this morning what the right defaults should be. I agree we should default to the YAML

**Comment by lazka** [comment]
It's enabled now.

**Comment by lazka** [comment]
@edglas1 Looks like PublishBuildArtifacts doesn't work for pull requests:

https://dev.azure.com/msys2/mingw/_build/results?buildId=29&view=logs

```
2018-09-19T08:47:37.5219809Z Fail to upload 'D:\a\1\s\artifacts\ci.mingw.builds' due to 'TF400813: The user 'd4bc076e-50fe-432b-84f5-83545a93b9e7' is not authorized to access this resource.'.
2018-09-19T08:47:37.5221288Z Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: The user 'd4bc076e-50fe-432b-84f5-83545a93b9e7' is not authorized to access this resource.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.<UploadFileAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.<UploadFileAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.FileContainerServer.<UploadAsync>d__14.MoveNext()
```

(Not sure if I should report it here, feel free to point me to some other support channel)

**Comment by lazka** [comment]
I've found some official comment for the error: https://github.com/Linuxbrew/brew/issues/746#issuecomment-422955300
