### ISSUE TITLE
python 2 error

### ISSUE THREAD

**Issue by AlexanderMisel** [Alexpux/MINGW-packages#4471]
I updated python2 to 2.7.15 and I run the following command
```bash
python -m SimpleHTTPServer 8080
```
and python outputs following errors
```bash
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "D:\git-sdk-64\mingw64\lib\python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
```

**Comment by Alexpux** [comment]
@AlexanderMisel  it works for me

**Comment by AlexanderMisel** [comment]
I am using Win7 x64. I cleared the pacman cache and reinstalled python2, but it still gets errors.

**Comment by stahta01** [comment]
Try using "pacman -Syuu"

Tim S.

**Comment by AlexanderMisel** [comment]
I was using the python from mingw64/bin, and the error only comes with this. I tried python2 from usr/bin and it works fine.

**Comment by spl1inter** [comment]
Probably because usr/bin is MSYS version built on minimal posix runtime (Cygwin-derived I believe). mingw64/bin runs direct native Windows API calls without the posix emulation. These two frameworks use separate DLLs. Likely the openssl DLL in MSYS is correct but the openssl being used by MINGW is wrong/outdated.
