### ISSUE TITLE
pip3 install pexpect fails after python3 updated to 3.7.1

### ISSUE THREAD

**Issue by gbtami** [Alexpux/MINGW-packages#4573]
I'v faced this error on Appveyor today:
```
python3 --version
Python 3.7.1
pip3 install pexpect
Traceback (most recent call last):
  File "C:\msys64\MINGW32\bin\pip3-script.py", line 11, in <module>
    load_entry_point('pip==18.0', 'console_scripts', 'pip3')()
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pkg_resources\__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pkg_resources\__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pkg_resources\__init__.py", line 2332, in load
    return self.resolve()
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pkg_resources\__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\index.py", line 24, in <module>
    from pip._internal.download import HAS_TLS, is_url, path_to_url, url_to_path
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\download.py", line 34, in <module>
    from pip._internal.locations import write_delete_marker_file
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\locations.py", line 17, in <module>
    USER_CACHE_DIR = appdirs.user_cache_dir("pip")
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\utils\appdirs.py", line 38, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\utils\appdirs.py", line 194, in _get_win_folder_from_registry
    import _winreg
ModuleNotFoundError: No module named '_winreg'
```

**Comment by lazka** [comment]
See #4572. It's being worked on.
