### ISSUE TITLE
python3: conflict between vendored and system packages

### ISSUE THREAD

**Issue by lazka** [Alexpux/MINGW-packages#4623]
```
$ pip3 list -o
Exception:
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.7/site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\pip\_internal\commands\list.py", line 136, in run
    packages = self.get_outdated(packages, options)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\pip\_internal\commands\list.py", line 147, in get_outdated
    dist for dist in self.iter_packages_latest_infos(packages, options)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\pip\_internal\commands\list.py", line 148, in <listcomp>
    if dist.latest_version > dist.parsed_version
TypeError: '>' not supported between instances of 'Version' and 'Version'
```

From a quick look, setuptools vendors packaging/six/pyparsing, which probably clashes with the system ones. We should try removing those and add them as package dependencies instead.

**Comment by lazka** [comment]
Or we could revert #4379 so that pip uses it's vendored deps.

@Alexpux should we unbundle the dependencies of setuptools like we currently do with pip or let setuptools+pip include all their dependencies?

**Comment by Alexpux** [comment]
I think we can try to unbundle deps
