### ISSUE TITLE
pkg_resources missing for meson

### ISSUE THREAD

**Issue by albfan** [Alexpux/MINGW-packages#4659]
trying to use meson in a fresh install of msys2 I get:

```
$ meson --version
Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\meson-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

I try installing meson and setuptools packages:

```
$ pacman -Q | grep "meson\|setuptools"
mingw-w64-i686-meson 0.48.2-1
mingw-w64-i686-python3-setuptools 40.5.0-2
mingw-w64-x86_64-meson 0.48.2-1
mingw-w64-x86_64-python2-setuptools 40.5.0-2
mingw-w64-x86_64-python3-setuptools 40.5.0-2
python3-setuptools 40.5.0-1
```

Maybe related https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909440

seems we need python3-pkg-resources

**Comment by mati865** [comment]
There is no such package as `python-pkg-resources`.
Most likely `python-setuptools` is broken, [see Arch Linux workaround](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/python-setuptools#n34).

**Comment by albfan** [comment]
I added that and try to build again setuptools, but it fails

```
MINGW64 ~/proyectos/MINGW-packages/mingw-w64-python-setuptools
$ makepkg -sif
==> Creando el paquete: mingw-w64-python-setuptools 40.5.0-2 (ju., 15 de nov. de 2018 14:03:40)
==> Comprobando dependencias mientras se ejecuta…
==> Comprobando dependencias mientras se compila…
==> Recibiendo las fuentes…
  -> setuptools-40.5.0.tar.gz ha sido encontrado
  -> 0001-mingw-python-fix.patch ha sido encontrado
  -> 0002-Allow-usr-bin-env-in-script.patch ha sido encontrado
  -> 0003-MinGW-w64-Look-in-same-dir-as-script-for-exe.patch ha sido encontrado
  -> 0004-dont-execute-msvc.patch ha sido encontrado
  -> 0005-execv-warning-patch ha sido encontrado
==> Validando los archivos source con sha256sums…
    setuptools-40.5.0.tar.gz ... Aprobado
    0001-mingw-python-fix.patch ... Aprobado
    0002-Allow-usr-bin-env-in-script.patch ... Aprobado
    0003-MinGW-w64-Look-in-same-dir-as-script-for-exe.patch ... Aprobado
    0004-dont-execute-msvc.patch ... Aprobado
    0005-execv-warning-patch ... Aprobado
==> Extrayendo las fuentes…
  -> Extrayendo setuptools-40.5.0.tar.gz con bsdtar
==> Iniciando prepare()…
patching file setuptools/command/easy_install.py
Hunk #1 succeeded at 1355 (offset 99 lines).
patching file launcher.c
patching file launcher.c
patching file setuptools/monkey.py
Hunk #1 succeeded at 98 (offset 8 lines).
patching file launcher.c
==> Eliminando el directorio $pkgdir/…
==> Iniciando build()…
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing setuptools.egg-info/PKG-INFO
writing top-level names to setuptools.egg-info/top_level.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing setuptools.egg-info/PKG-INFO
writing top-level names to setuptools.egg-info/top_level.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
Regenerating egg_info
...and again.
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "C:/msys64/mingw64/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
running build
running build_py
creating build/lib/pkg_resources/_vendor
copying pkg_resources/_vendor/appdirs.py -> build/lib/pkg_resources/_vendor
copying pkg_resources/_vendor/pyparsing.py -> build/lib/pkg_resources/_vendor
copying pkg_resources/_vendor/six.py -> build/lib/pkg_resources/_vendor
copying pkg_resources/_vendor/__init__.py -> build/lib/pkg_resources/_vendor
creating build/lib/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/markers.py -> build/lib/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/requirements.py -> build/lib/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/specifiers.py -> build/lib/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/utils.py -> build/lib/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/version.py -> build/lib/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/_compat.py -> build/lib/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/_structures.py -> build/lib/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/__about__.py -> build/lib/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/__init__.py -> build/lib/pkg_resources/_vendor/packaging
copying setuptools/command/easy_install.py -> build/lib/setuptools/command
creating build/lib/setuptools/_vendor
copying setuptools/_vendor/pyparsing.py -> build/lib/setuptools/_vendor
copying setuptools/_vendor/six.py -> build/lib/setuptools/_vendor
copying setuptools/_vendor/__init__.py -> build/lib/setuptools/_vendor
creating build/lib/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/markers.py -> build/lib/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/requirements.py -> build/lib/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/specifiers.py -> build/lib/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/utils.py -> build/lib/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/version.py -> build/lib/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/_compat.py -> build/lib/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/_structures.py -> build/lib/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/__about__.py -> build/lib/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/__init__.py -> build/lib/setuptools/_vendor/packaging
Regenerating egg_info
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "C:\msys64\home\afanjula\proyectos\MINGW-packages\mingw-w64-python-setuptools\src\setuptools-python3-x86_64\setuptools\__init__.py", line 11, in <module>
    from six import PY3
ModuleNotFoundError: No module named 'six'
Traceback (most recent call last):
  File "bootstrap.py", line 64, in <module>
    __name__ == '__main__' and main()
  File "bootstrap.py", line 61, in main
    run_egg_info()
  File "bootstrap.py", line 54, in run_egg_info
    subprocess.check_call(cmd)
  File "C:/msys64/mingw64/lib/python3.6\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:/msys64/mingw64/bin/python3.exe', 'setup.py', 'egg_info']' returned non-zero exit status 1.
==> ERROR: Se produjo un fallo en build().
    Cancelando…
```

I checked and I have six installed:

```
$ pacman -Q | grep \\-six
mingw-w64-i686-python2-six 1.11.0-2
mingw-w64-i686-python3-six 1.11.0-2
mingw-w64-x86_64-python2-six 1.11.0-2
mingw-w64-x86_64-python3-six 1.11.0-2
python3-six 1.11.0-1
```

@mati865 Any way to apply that patch into installed files? or downgrade meson or setuptools? this use to work for me

**Comment by mati865** [comment]
If this workaround made the package unbuildable it definitely shouldn't be applied as-is. Presumably it needs tweaks for MSYS2 `/mingw{32,64}` directories.

You can download meson older version from http://repo.msys2.org/mingw/x86_64/ but partial upgrades are not supported and it may break anytime.

**Comment by albfan** [comment]
Downgrade to meson 0.46.1 works for me. If anyone want me to try anything just tell me

**Comment by lazka** [comment]
Not sure if that related, but looking at your build logs it looks like you have installed an incompatible openssl again.

**Comment by albfan** [comment]
@lazka how do you detect that?

I was using meson 0.48 in other machine this happening in another one with a fresh install
