### ISSUE TITLE
pip3 broken

### ISSUE THREAD

**Issue by lazka** [Alexpux/MINGW-packages#4715]
I guess this is fixed by #4712 and #4711

```
Traceback (most recent call last):
  File "C:\msys64\mingw32\bin\pip3-script.py", line 11, in <module>
    load_entry_point('pip==18.1', 'console_scripts', 'pip3')()
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\cli\autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\cli\main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\commands\__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\commands\completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\cli\base_command.py", line 25, in <module>
    from pip._internal.req.constructors import (
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\req\__init__.py", line 5, in <module>
    from .req_install import InstallRequirement
  File "C:/msys64/mingw32/lib/python3.7/site-packages\pip\_internal\req\req_install.py", line 16, in <module>
    from pip._vendor.pep517.wrappers import Pep517HookCaller
ModuleNotFoundError: No module named 'pip._vendor.pep517'
```

**Comment by Alexpux** [comment]
Fixed

**Comment by lazka** [comment]
Thanks!
