### ISSUE TITLE
Please update python-requests to 2.21.0 (to fix python-sphinx)

### ISSUE THREAD

**Issue by k-takata** [Alexpux/MINGW-packages#4802]
The following error is shown when executing python-sphinx:

```
$ sphinx-build -b html -d _build/doctrees   . _build/html
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.7/site-packages\pkg_resources\__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\pkg_resources\__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:/msys64/mingw64/lib/python3.7/site-packages\pkg_resources\__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.8 (c:/msys64/mingw64/lib/python3.7/site-packages), Requirement.parse('idna<2.8,>=2.5'), {'requests'})
```

It seems that python-requests and python-idna are conflicting.
python-requests 2.20.1 requires idna<2.8 but idna is 2.8 now.
It seems that python-requests 2.21.0 supports idna 2.8: http://docs.python-requests.org/en/master/community/updates/#id1
So, please update python-requests to 2.21.0.

**Comment by k-takata** [comment]
Thank you.
