### ISSUE TITLE
mingw-w64-x86_64-asciidoctor newly broken!

### ISSUE THREAD

**Issue by angelog0** [Alexpux/MINGW-packages#4809]
Just installed MSYS2 on a new PC and

```
$ pacman -S  mingw-w64-x86_64-asciidoctor
[...]

$ pacman -Ss ruby | grep installato
mingw64/mingw-w64-x86_64-asciidoctor 1.5.8-1 [installato]
mingw64/mingw-w64-x86_64-ruby 2.6.0-1 [installato]

## in MINGW64 shell:
asciidoctor foo.adoc -o foo.html
C:/msys64/mingw64/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem asciidoctor (>= 0.a) with executable asciidoctor (Gem::GemNotFoundException)
        from C:/msys64/mingw64/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
        from C:/msys64/mingw64/bin/asciidoctor:23:in `<main>'
```

Each time I need it on MSYS2 it does not work!

**Comment by Alexpux** [comment]
@angelog0 will be fixed soon. Need rebuild asciidoctor with new ruby
