### ISSUE TITLE
meld 3: Couldn't load Meld-specific CSS (/mingw64/share/meld/meld.css)

### ISSUE THREAD

**Issue by magoyan** [Alexpux/MINGW-packages#597]
$ pacman -sS meld3
mingw32/mingw-w64-i686-meld3 3.13.0-1
    Visual diff and merge tool (mingw-w64)
mingw64/mingw-w64-x86_64-meld3 3.13.0-1 [installed]
    Visual diff and merge tool (mingw-w64)

It seems that meld tries to use a Unix path (/ mingw w64 / share / meld / meld.css) while using a native Python window

$ meld
Couldn't bind the translation domain. Some translations won't work.
[Error 126] The specified module could not be found
Couldn't load Meld-specific CSS (/mingw64/share/meld/meld.css)
gtk-css-provider-error-quark: Failed to import: Error opening file: No such file
or directory (2)
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/site-packages/meld/meldapp.py", line 62,
in do_startup
    builder = meld.ui.util.get_builder("application.ui")
  File "C:/msys64/mingw64/lib/python2.7/site-packages/meld/ui/util.py", line 40,
in get_builder
    builder.add_from_file(ui_file(filename))
GLib.Error: g-file-error-quark: Failed to open file
'/mingw64/share/meld/ui/application.ui': No such file or directory (4)
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/site-packages/meld/meldapp.py", line 69,
in do_activate
    self.get_active_window().present()
AttributeError: 'NoneType' object has no attribute 'present'
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/site-packages/meld/meldapp.py", line 73,
in do_command_line
    tab = self.parse_args(command_line)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/meld/meldapp.py", line
316, in parse_args
    focus=i == 0)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/meld/meldapp.py", line
142, in open_files
    window = self.get_meld_window()
  File "C:/msys64/mingw64/lib/python2.7/site-packages/meld/meldapp.py", line
137, in get_meld_window
    return self.get_active_window().meldwindow
AttributeError: 'NoneType' object has no attribute 'meldwindow'

**Comment by Alexpux** [comment]
I'm upload meld3-3.13.1. Hope it fix problem

**Comment by magoyan** [comment]
Fixed ! Thanks a lot .
