### ISSUE TITLE
matplotlib-1.5.0rc2 module import error

### ISSUE THREAD

**Issue by oroppas** [Alexpux/MINGW-packages#822]
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.5/site-packages\matplotlib\__init__.py", line 124, in <module>
    from matplotlib.rcsetup import (defaultParams,
  File "C:/msys64/mingw64/lib/python3.5/site-packages\matplotlib\rcsetup.py", line 29, in <module>
    from cycler import Cycler, cycler as ccycler
ImportError: No module named 'cycler'

**Comment by tunabrain** [comment]
I am having the same issue. Matplotlib used to work fine, but I recently upgraded my installation from `mingw-w64-x86_64-python3-matplotlib 1.4.3-1` to `1.5.0rc2-1` and since then it is broken.

For reference, the missing module is this one: https://github.com/matplotlib/cycler

After I install it manually, this error disappears, and I am instead greeted with

```
Traceback (most recent call last):
  File "./plot.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "D:/msys64/mingw64/lib/python3.5/site-packages\matplotlib\pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "D:/msys64/mingw64/lib/python3.5/site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "D:/msys64/mingw64/lib/python3.5/site-packages\matplotlib\backends\backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "D:/msys64/mingw64/lib/python3.5/site-packages\matplotlib\backends\backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "D:/msys64/mingw64/lib/python3.5/site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 17, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "D:/msys64/mingw64/lib/python3.5/site-packages\matplotlib\backends\qt_editor\formlayout.py", line 58, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "D:/msys64/mingw64/lib/python3.5/site-packages\matplotlib\backends\qt_compat.py", line 144, in <module>
    raise RuntimeError("PyQt{4,5} bindings found despite sip importing\n"
RuntimeError: PyQt{4,5} bindings found despite sip importing
Please install PyQt4 or PyQt5, uninstall sip or explicitly set the pyside backend.
```

PyQt5 is installed (`mingw-w64-x86_64-python3-pyqt5`), but it depends on sip, so I can't remove that as the exception suggests.

Brief googling shows that this might be an issue with matplotlib 1.5, so maybe downgrading to 1.4 fixes it?

**Comment by tunabrain** [comment]
Just upgraded from `1.5.0rc2-1` to `1.5.0-1` and can confirm that the problem persists.

**Comment by oroppas** [comment]
Thanks for the confirmation. I hoped 1.5.0 would fix the issue but that is
not the case. I've checked the Arch Linux website and their matplotlib
depends on python-cycler. Let me see if I can come up with PKGBUILD for
python-cycler...

**Comment by dfense** [comment]
Having near identical issue. Most stripped out version I can with matplotlib , and I get a good run on pyinstaller , but when it runs get 

dfense:~/Qt5.5/projects/test6$ ./dist/plot/plot 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 124, in <module>
    from matplotlib.rcsetup import (defaultParams,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/rcsetup.py", line 29, in <module>
    from cycler import Cycler, cycler as ccycler
ImportError: No module named 'cycler'
plot returned -1


Using python 3.5.1, matplotlib 1.5.0 pyinstaller 3.0
I have PyQt5 installed, and if i dereference marplotlib in my program, compiles and executes fine after pyinstaller is completed.

**Comment by oroppas** [comment]
Copy and paste the following into PKGBUILD and matplotlib-1.5.0 will be back to normal.
I tested on x86_64 + python3. Untested on other platforms, but it should work.
Anyone willing to volunteer to test?

pkgbase="mingw-w64-python-cycler"
pkgname=(
  "${MINGW_PACKAGE_PREFIX}-python3-cycler"
  ${MINGW_PACKAGE_PREFIX}-"python2-cycler"
)
pkgver=0.9.0
pkgrel=1
pkgdesc="Composable style cycles"
arch=('any')
license=('BSD')
url="http://github.com/matplotlib/cycler"
makedepends=(
  "${MINGW_PACKAGE_PREFIX}-python3-setuptools"
  "${MINGW_PACKAGE_PREFIX}-python2-setuptools"
  "${MINGW_PACKAGE_PREFIX}-python3-six"
  "${MINGW_PACKAGE_PREFIX}-python2-six"
  'git')
checkdepends=(
  "${MINGW_PACKAGE_PREFIX}-python3-nose"
  "${MINGW_PACKAGE_PREFIX}-python2-nose"
  "${MINGW_PACKAGE_PREFIX}-python3-coverage"
  "${MINGW_PACKAGE_PREFIX}-python2-coverage"
)
source=("git+https://github.com/matplotlib/cycler.git#tag=v$pkgver")
sha512sums=('SKIP')

prepare() {
  cp -a cycler{,-py2}
}

build() {
  cd "$srcdir/cycler"
  python3 setup.py build

  cd "$srcdir/cycler-py2"
  python2 setup.py build
}

check() {
  cd "$srcdir/cycler"
  python3 run_tests.py

  cd "$srcdir/cycler-py2"
  python2 run_tests.py
}

package_python3-cycler() {
  depends=(
    "${MINGW_PACKAGE_PREFIX}-python3>=3.5.0" "${MINGW_PACKAGE_PREFIX}-python3<3.6.0"
    "${MINGW_PACKAGE_PREFIX}-python3-six"
  )

  cd cycler
  python3 setup.py install --root="${pkgdir}" --prefix=/$MINGW_PREFIX --optimize=1
  install -D -m644 LICENSE "${pkgdir}/$MINGW_PREFIX/share/licenses/python3-cycler/LICENSE"
}

package_python2-cycler() {
  depends=(
    "${MINGW_PACKAGE_PREFIX}-python2-six"
    "${MINGW_PACKAGE_PREFIX}-python2>=2.7.0" "${MINGW_PACKAGE_PREFIX}-python2<2.8.0"
    "${MINGW_PACKAGE_PREFIX}-python2-six"
  )

  cd cycler-py2
  python2 setup.py install --root="${pkgdir}" --prefix=/$MINGW_PREFIX --optimize=1
  install -D -m644 LICENSE "${pkgdir}/$MINGW_PREFIX/share/licenses/python2-cycler/LICENSE"
}

package_mingw-w64-i686-python2-cycler() {
  package_python2-cycler
}

package_mingw-w64-i686-python3-cycler() {
  package_python3-cycler
}

package_mingw-w64-x86_64-python2-cycler() {
  package_python2-cycler
}

package_mingw-w64-x86_64-python3-cycler() {
  package_python3-cycler
}

**Comment by Alexpux** [comment]
Create pull request instead paste PKGBUILD here. Also add cycler as dependency for matplotlib

**Comment by oroppas** [comment]
Done.
