### ISSUE TITLE
msys python3.4   matplotlib1.5.0  TypeError: unorderable types: str() < int()

### ISSUE THREAD

**Issue by ongbe** [Alexpux/MINGW-packages#910]
Traceback (most recent call last):
  File "setup.py", line 271, in <module>
    result = package.check()
  File "/f/tc/msys32/home/Owner/msys2_build_recipes/MINGW-packages/mingw-w64-python-matplotlib/src/matplotlib-py3-1.5.0/setupext.py", line 933, in check
    min_version='2.3', version=version)
  File "/f/tc/msys32/home/Owner/msys2_build_recipes/MINGW-packages/mingw-w64-python-matplotlib/src/matplotlib-py3-1.5.0/setupext.py", line 475, in _check_for_pkg_config
    if (not is_min_version(version, min_version)):
  File "/f/tc/msys32/home/Owner/msys2_build_recipes/MINGW-packages/mingw-w64-python-matplotlib/src/matplotlib-py3-1.5.0/setupext.py", line 184, in is_min_version
    return found_version >= expected_version
  File "/usr/lib/python3.4/distutils/version.py", line 76, in __ge__
    c = self._cmp(other)
  File "/usr/lib/python3.4/distutils/version.py", line 343, in _cmp
    if self.version < other.version:
TypeError: unorderable types: str() < int()

**Comment by Alexpux** [comment]
Seems you mix MINGW/MSYS2 python's
