### ISSUE TITLE
mingw-w64-python-ipython does not install its dependencies

### ISSUE THREAD

**Issue by Arnie97** [Alexpux/MINGW-packages#937]
```yaml
$ pacman -Sy mingw-w64-i686-python3-ipython
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
resolving dependencies...
looking for conflicting packages...

Packages (2) mingw-w64-i686-sqlite3-3.9.2.0-1
             mingw-w64-i686-python3-ipython-4.0.0-1

Total Installed Size:  5.75 MiB

:: Proceed with installation? [Y/n]
(2/2) checking keys in keyring                     [#####################] 100%
(2/2) checking package integrity                   [#####################] 100%
(2/2) loading package files                        [#####################] 100%
(2/2) checking for file conflicts                  [#####################] 100%
(2/2) checking available disk space                [#####################] 100%
(1/2) installing mingw-w64-i686-sqlite3            [#####################] 100%
(2/2) installing mingw-w64-i686-python3-ipython    [#####################] 100%
Optional dependencies for mingw-w64-i686-python3-ipython
    mingw-w64-i686-python3-nose: for IPython's test suite
    mingw-w64-i686-python3-pyqt4: for ipython qtconsole
    mingw-w64-i686-python3-sip: for ipython qtconsole
    mingw-w64-i686-python3-pygments: for ipython qtconsole
    mingw-w64-i686-python3-jinja: for ipython notebook
```
```python
$ ipython
Traceback (most recent call last):
  File "X:/Msys/mingw32/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "X:/Msys/mingw32/lib/python3.5/site-packages\IPython\__init__.py", line 47, in <module>
    from .core.application import Application
  File "X:/Msys/mingw32/lib/python3.5/site-packages\IPython\core\application.py", line 22, in <module>
    from traitlets.config.application import Application, catch_config_error
ImportError: No module named 'traitlets'
```

**Comment by Arnie97** [comment]
`pip3 install ipython` just works.
But it will install `ipython` as a binary, which stops me from workarounds in #730.

**Comment by DavidEGrayson** [comment]
You might try running `pip3 install traitlets` to get the missing dependency.  But I think the long term solution would be to add a MSYS2 traitlets package.
